<?php

namespace Tests\Unit;

use Illuminate\Support\Facades\File;
use Tests\TestCase;

class ControllersCommandTest extends TestCase
{

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        File::delete(app_path('Http/Controllers/Auth/ResetEmailController.php'));
    }

    public function testDriverConfig()
    {
        $this
            ->artisan('email-reset:controllers')
            ->expectsOutput('EmailReset scaffolding generated successfully.')
            ->assertExitCode(0);
        $this->assertFileExists(app_path('Http/Controllers/Auth/ResetEmailController.php'));
    }
}
